services:

  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins-ui
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  test-runner:
    build:
      context: .
    container_name: playwright-tests
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ./bin/test-runner-entrypoint.sh

volumes:
  jenkins_home:
