name: Autoformat with Black

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Fetch all remote branches
        run: git fetch --all

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Get modified files
        id: changed
        run: |
          files=$(git diff --name-only origin/${{ github.base_ref }} -- '*.py' | xargs)
          echo "$files" > changed_files.txt
          echo "files=$files" >> $GITHUB_OUTPUT

      - name: Run Black
        if: steps.changed.outputs.files != ''
        run: |
          poetry run black --verbose --config pyproject.toml $(cat changed_files.txt)

      - name: Commit and push changes
        if: steps.changed.outputs.files != ''
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add $(cat changed_files.txt)
          git commit -m "Apply Black formatting" || echo "No changes to commit"
          git push
