name: Autoformat with Black

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Run Black
        run: |
          poetry run black --config pyproject.toml .

      - name: Create a new branch and push formatting changes
        run: |
          branch_name="black-fixes/${{ github.head_ref }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      
          if [[ -n $(git status --porcelain) ]]; then
            git checkout -b "$branch_name"
            git add .
            git commit -m "Apply Black formatting"
            git push origin "$branch_name"
      
            echo "needs_pr=true" >> $GITHUB_ENV
          else
            echo "No formatting changes detected"
            echo "needs_pr=false" >> $GITHUB_ENV
          fi

      - name: Create a PR with Black fixes
        if: env.needs_pr == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --head "black-fixes/${{ github.head_ref }}" \
                       --base "${{ github.head_ref }}" \
                       --title "Apply Black formatting" \
                       --body "This PR applies auto-formatting using Black."
      
