name: Lint

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch origin main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Get modified Python files
        id: changed
        run: |
          files=$(git diff --name-only origin/main...HEAD -- '*.py')
          echo "files=$(echo "$files" | paste -sd " " -)" >> "$GITHUB_OUTPUT"

      - name: Run linters
        if: steps.changed.outputs.files != ''
        run: |
          set -e
          files="${{ steps.changed.outputs.files }}"
          echo "Running linters on: $files"

          # Run Pylint
          poetry run pylint $files || pylint_status=$?

          # Run Vulture
          poetry run vulture $files || vulture_status=$?

          # Run Mypy
          poetry run mypy --explicit-package-bases $files || mypy_status=$?

          # Run Black
          poetry run black --check --config pyproject.toml $files || black_status=$?

          # Sum up results
          exit_code=0
          [ "$pylint_status" ] && exit_code=1
          [ "$vulture_status" ] && exit_code=1
          [ "$mypy_status" ] && exit_code=1
          [ "$black_status" ] && exit_code=1

          exit $exit_code
