name: Lint

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Get modified Python files
        id: changed
        run: |
          files=$(git diff --name-only origin/main...HEAD | grep '\.py$' || true)
          echo "files=$files" >> $GITHUB_OUTPUT

      - name: Run Pylint
        if: steps.changed.outputs.files != ''
        run: |
          poetry run pylint ${{ steps.changed.outputs.files }}

      - name: Run Vulture
        if: steps.changed.outputs.files != ''
        run: |
          poetry run vulture ${{ steps.changed.outputs.files }}
